# Source: https://gist.github.com/philip-gai/2b21293b178aa6ea6903e99cc1c32c4f
# Prerequisites:
# - Create a secret with your PAT token. Permissions needed: repo (all) and read:org
# - Create the HELLO_WORLD secret in your environment with some dummy initial value
# 
# Notes:
# - You can tell that it works because it masks the secret_body in the echo secret step after it creates the secret 😄
# - If you don't want to have to call gh auth login, set the env var GH_TOKEN or GITHUB_TOKEN to ${{ secrets.PAT_TOKEN }} and skip that step
# - If you don't want to have to pass --repo to gh secret set, then put the actions/checkout@v2 step before the gh secret set step
# 

name: gh-set-secret

on:
  workflow_dispatch:
  
env:
  pat_token: ${{ secrets.PAT_TOKEN }}
  secret_name: HELLO_WORLD
  secret_body: "Hello World!"
  secret_repo: "hauw0014/cordova-leaflet-template"
  secret_environment: dev

jobs:
  gh-set-secret:
    runs-on: ubuntu-latest
    steps:
      - name: gh auth login
        shell: bash
        run: gh auth login --with-token <<< "${{ env.pat_token }}"
      - name: gh secret set env
        shell: bash
        run: gh secret set "${{ env.secret_name }}" --env "${{ env.secret_environment }}" --body "${{ env.secret_body }}" --repo "${{ env.secret_repo }}"
  gh-test-secret:
    needs: [gh-set-secret]
    runs-on: ubuntu-latest
    environment:
      name: dev
    env:
      secret: ${{ secrets.HELLO_WORLD }}
    steps:
      - name: echo secret
        shell: bash
        run: echo "$HELLO_WORLD"
